variables:
  repository: 'jannemattila/webapp-myip'

trigger:
- main
- develop

name: 1.1.$(Rev:r)
stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub'
        repository: $(repository)
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        buildContext:
        tags: |
          $(Build.BuildNumber)
          latest
